# Create a dedicated namespace for OpenShift GitOps
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
---
# Create an OperatorGroup resource for the openshift-gitops namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name:  openshift-gitops-operator-group
  namespace:  openshift-gitops-operator
spec:
  upgradeStrategy: Default
---
# Create a subscription for the GitOps operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
