# Create a dedicated namespace for Dev Spaces
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-devspaces
  name: openshift-devspaces
---
# Create an OperatorGroup resource for the devspaces namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name:  devspaces-operator-group
  namespace:  openshift-devspaces
---
# Create a subscription for the Dev Spaces Operator (DO)
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-devspaces
  namespace: openshift-devspaces
spec:
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: devspaces
---
